= MUnit Maven プラグインを操作する方法
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

このセクションでは、プラグインを使用してテストを実行する方法のみを説明します。

== Mule アプリケーションの MUnit テストを実行する方法 (MUnit Maven プラグイン)

.単一リソース Mule プロジェクトで MUnit テストを実行します。
[source,console]
----
mvn clean test
----

アプリケーションがマルチモジュールアプリケーションの場合:

. アプリケーションの POM ファイルで Mule ドメイン連動関係が provided とマークされていることを確認します。
+
.Mule アプリケーションの POM ファイルで Mule ドメインを連動関係として追加します。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. `mvn test` ではなく `mvn install` を実行します。
+
[source,console]
----
mvn clean install
----

== 特定の MUnit テストスイートを実行する方法 (MUnit Maven プラグイン)

特定のテストスイートに属するテストのみを実行するように MUnit Maven プラグインに指示できます。

これを行うには、プロパティ `munit.test` を使用します。

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>
----

アプリケーションがマルチモジュールアプリケーションの場合:

. アプリケーションの POM ファイルで Mule ドメイン連動関係が provided とマークされていることを確認します。
+
.Mule アプリケーションの POM ファイルで Mule ドメインを連動関係として追加します。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. `mvn test` ではなく `mvn install` を実行します。
+
[source,console]
----
mvn clean install -Dmunit.test=<regex-test-suite>
----

プロパティ `munit.test` は、正規表現に対応しています。この式は、MUnit テストスイートファイルの名前に適用されます。正規表現の言語は Java 実装です。 +
このパスは、src/test/munit に対して相対的です。

次に、有効な例を示します。
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*
----

この機能を利用するには、命名規則を MUnit テストスイートに追加します。

== 特定の MUnit テストを実行する方法 (MUnit Maven プラグイン)

1 つのテストスイートを実行するように MUnit に指示する場合と同じ方法で、テストスイート内の特定のテストを実行するように MUnit に指示できます。これを行うには、プロパティ `munit.test` を再度利用します。ただし、1 つの追加部分があります。

[source,console]
----
mvn clean test -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

アプリケーションがマルチモジュールアプリケーションの場合:

. アプリケーションの POM ファイルで Mule ドメイン連動関係が provided とマークされていることを確認します。
+
.Mule アプリケーションの POM ファイルで Mule ドメインを連動関係として追加します。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. `mvn test` ではなく `mvn install` を実行します。
+
[source,console]
----
mvn clean install -Dmunit.test=<regex-test-suite>#<regex-test-name>
----

特殊文字 `#` が追加されています。その右側には、テスト名を入力する必要があります。これも、正規表現に対応しています。式は、MUnit テストの属性 `name` に適用されます。

次に、有効な例を示します。
[source,console]
----
mvn clean test -Dmunit.test=.*my-test.*#.*test-scenario-1.*
----

[TIP]
--
正規表現に一致しない MUnit テストスイート内のテストは、*ignored* フラグが設定されます。
--

== 特定のタグを使用してテストを実行する方法 (MUnit Maven プラグイン)

1 つの特定のタグでグループ化したテストのみを実行できます。

[source,console]
----
mvn clean test -Dmunit.tags=<munit-tag>
----

アプリケーションがマルチモジュールアプリケーションの場合:

. アプリケーションの POM ファイルで Mule ドメイン連動関係が provided とマークされていることを確認します。
+
.Mule アプリケーションの POM ファイルで Mule ドメインを連動関係として追加します。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. `mvn test` ではなく `mvn install` を実行します。
+
[source,console]
----
mvn clean install -Dmunit.tags=<munit-tag>
----


== すべてのテストをスキップする方法 (MUnit Maven プラグイン)

アプリケーションの構築時に、テストの実行を回避できます。MUnit は Maven と同じメカニズムを利用しているため、テストをスキップする場合、パラメータ `skipTests` を利用できます。

.テストのスキップの例
[source,console]
----
mvn clean package -DskipTests
----

アプリケーションがマルチモジュールアプリケーションの場合:

. アプリケーションの POM ファイルで Mule ドメイン連動関係が provided とマークされていることを確認します。
+
.Mule アプリケーションの POM ファイルで Mule ドメインを連動関係として追加します。
[source,xml,linenums]
----
<dependency>
    <groupId>org.mule.app</groupId>
    <artifactId>domain-project</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <classifier>mule-domain</classifier>
    <scope>provided</scope>
</dependency>
----
. `mvn test` ではなく `mvn install` を実行します。
+
[source,console]
----
mvn clean install -DskipTests
----

// _COMBAK: No Java test for now.
// == To Skip Only MUnit Tests (MUnit Maven Plugin)
//
// MUnit also comes with another property that only prevents MUnit tests from running.
// While at the same time allowing any other test, like JUnit tests, to keep running.
//
// If you wish to skip only MUnit tests, you can make use of the parameter `skipMunitTests`.
//
// [source,console]
// .Skipping MUnit Tests example
// ----
// mvn clean package -DskipMunitTests
// ----
//
// If your application is a multi-module application:
//
// . Make sure your mule-domain dependency is marked as provided in your application's POM file.
// +
// .Add your Mule Domain as a Dependency in your Mule Application POM File.
// [source,xml,linenums]
// ----
// <dependency>
//     <groupId>org.mule.app</groupId>
//     <artifactId>domain-project</artifactId>
//     <version>1.0.0-SNAPSHOT</version>
//     <classifier>mule-domain</classifier>
//     <scope>provided</scope>
// </dependency>
// ----
// . Run `mvn install`, instead of `mvn test`.
// +
// [source,console]
// ----
// mvn clean install -DskipMunitTests
// ----
//
// TIP: The property `skipMunitTests` applies only to the XML based MUnit tests.

== 関連情報

* xref:faq-how-to-read-munit-test-results.adoc[FAQ: MUnit テスト結果を読み取る方法]
