= Run Custom イベントプロセッサについて
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:version-info: 2.0 以降
:keywords: mule, esb, テスト, QA, 品質保証, 検証, 機能テスト, ユニットテスト, ストレステスト

Run Custom イベントプロセッサを使用すると、Mule イベントコンテンツをカスタムアサーションに対して確認できます。

たとえば、JAVA で次のアサーションを定義できます。

[source,java,linenums]
----
public class CustomAssertion implements MunitAssertion {

    @Override
    public void execute(TypedValue expression, Object params) throws AssertionError { // <1>
        if (!"Hello World".equals(expression.getValue())) { // <2>
            throw new AssertionError("Error the payload is incorrect");
        }
     }

}
----
<1> インターフェースに 1 つのメソッドのみを実装します: `public void execute(TypedValue expression, Object params) throws AssertionError`
<2> カスタムロジックを実行します。この場合は、メッセージのペイロードが `Hello World` であることを検証します。

次に、Run Custom イベントプロセッサを使用してこれを実行します。

[source,xml,linenums]
----
<munit-tools:run-custom
  assertion="com.example.CustomAssertion" // <1>
  expression="#[payload]"/>
----
<1> アサーション項目にカスタムアサーションの正規クラス名が含まれている必要があります。

// _TODO:Comment out and check with the team
// [CAUTION]
// --
// Implement your custom assertions with care. Modifying the message payload or variables could affect subsequent assertions in your test. Normal MUnit assertions guarantee that this does not happens unless specified
// --



== 関連情報

* xref:munit-matchers.adoc[MUnit マッチャーについて]
* xref:assertion-message-processor.adoc[Assert That イベントプロセッサについて]
* xref:set-message-processor.adoc[Set Event プロセッサについて]
* xref:mock-message-processor.adoc[Mock When イベントプロセッサについて]
* xref:verify-message-processor.adoc[Verify イベントプロセッサについて]
* xref:fail-event-processor.adoc[Fail イベントプロセッサについて]
